fix webmachine compilation error (upgrade to latest master)
===> Compiling _build/default/lib/webmachine/src/webmachine_resource.erl failed
_build/default/lib/webmachine/src/webmachine_resource.erl:205: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

Signed-off-by: Lincoln Baker <lbaker@chef.io>